services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bloom
      POSTGRES_PASSWORD: bloom
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bin/rails db:prepare && bin/rails db:seed && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://bloom:bloom@db:5432/bloom_coffee_development
    tty: true
    stdin_open: true

volumes:
  postgres_data:
  bundle_cache:
