source "https://rubygems.org"

ruby ">= 3.1.0"

gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-activerecord"
gem "rack-cors"
gem "dotenv"
gem "jwt"
gem "bcrypt"
gem "activerecord"
gem "sqlite3"
gem "pg"
gem "rake"

gem "rackup", "~> 2.3"

gem "puma", "~> 8.0"
